name: azure-deployment-pipeline
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/azure-project

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      # Install the latest version of the Terraform CLI
      #   - name: Setup Terraform
      #     uses: hashicorp/setup-terraform@v2
      #     with:
      #       terraform_wrapper: false

      #   # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      #   - name: Terraform Init
      #     run: terraform init

      #   # Checks that all Terraform configuration files adhere to a canonical format
      #   # Will fail the build if not
      #   - name: Terraform Format
      #     run: terraform fmt -check

      #   - name: Terraform validate
      #     id: validate
      #     run: terraform validate -no-color

      #   - name: Terraform plan
      #     id: plan
      #     run: terraform plan -no-color

      #   - name: Terraform apply
      #     id: apply
      #     run: terraform apply -auto-approve

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Extract Version from Dockerfile
        id: extract_version
        run: echo "::set-output name=version::$(grep -oP '(?<=version=")[^"]*' Dockerfile)"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}:${{steps.extract_version.outputs.version }}

      - name: Push to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${{env.IMAGE_NAME}}:${{steps.extract_version.outputs.version }}
          docker tag ${{env.IMAGE_NAME}}:${{steps.extract_version.outputs.version }} ${{env.IMAGE_NAME}}:latest
          docker push ${{env.IMAGE_NAME}}:latest

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/${{env.IMAGE_NAME}}:lastest"
